services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      AUTH_TYPE: scram-sha-256
    volumes:
      - ./db:/etc/pgbouncer
    ports:
      - "6432:6432"
    command: >
      pgbouncer -u postgres
      /etc/pgbouncer/pgbouncer.ini
